version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PRODUCTION: "false"
    container_name: nx-backend-dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - /apps/backend/.env.development
    environment:
      NODE_ENV: development
      PRODUCTION: "false"
    command: sh -c "npx nx run backend:dev"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PRODUCTION: "false"
    container_name: nx-frontend-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - /apps/frontend/.env.local
    environment:
      NODE_ENV: development
      PRODUCTION: "false"
    command: sh -c "npx nx run frontend:dev"

  supabase-db:
    image: supabase/postgres:15.1.0.121
    container_name: supabase-dev-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - supabase-dev-data:/var/lib/postgresql/data

volumes:
  supabase-dev-data:
